name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4

        # run: echo aaaa

        with:
          browser: chrome
          record: true
          wait-on: 'http://dev-app.ontum.co'
          command-prefix: 'yarn'

        env:
          # pass the Dashboard record key as an environment variable
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
            URL="${{ secrets.WEBHOOK_URL }}"
            curl -X POST -d {} "$URL" -H "Content-Type: application/json"