name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4

        with:
          browser: chrome
          record: true
          path: cypress\videos

        env:
          # pass the Dashboard record key as an environment variable
            CYPRESS_RECORD_KEY: ${{ secrets.28d80ecb-8567-4144-8c19-3ae7f9a51efe }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
            GITHUB_TOKEN: ${{ secrets.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 }}